SELECT * FROM EMP NATURAL JOIN DEPT;

SELECT * FROM SALGRADE;

SELECT * 
FROM DEPT NATURAL JOIN SALGRADE;

SELECT * 
from emp E, DEPT d where E.DEPTNO = d.DEPTNO;

UPDATE EMP  SET DEPTNO = NULL WHERE EMPNO = 7934;

SELECT * FROM EMP;

SELECT * 
FROM EMP, DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO;

UPDATE EMP  SET DEPTNO = 10 WHERE EMPNO = 7934;

SELECT * 
FROM EMP, DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO;

SELECT * 
FROM emp full outer join dept d on emp.deptno = d.deptno;

SELECT * FROM EMP;

-- NATURAL JOIN

SELECT * FROM EMP E1 JOIN EMP E2 ON E1.MGR = E2.EMPNO;

-- QUERY TO DISPLAY EMPNAME, SAL, MANAGER NAME, MANAGER JOB IF EMP SAL > 2000
SELECT E1.ENAME, E1.SAL, E2.ENAME AS MANAGER_NAME, E2.JOB
FROM EMP E1 JOIN EMP E2 ON E1.MGR = E2.EMPNO
WHERE E1.SAL > 2000;

-- employee name, job, manager name if manager hiredate if manager is hired before the year 82
SELECT E1.ENAME, E1.JOB, E2.ENAME AS MANAGER_NAME, E2.HIREDATE
FROM EMP E1 JOIN EMP E2 ON E1.MGR = E2.EMPNO
WHERE TO_CHAR(E2.HIREDATE, 'YY') < '82';

