-- SUBQUERIES

SELECT * FROM EMP 
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'ALLEN');

-- condition on another Table  

SELECT DNAME FROM DEPT WHERE DEPTNO = (SELECT DEPTNO FROM EMP 
                                     WHERE ENAME = 'SCOTT');

SELECT ENAME 
FROM EMP 
WHERE SAL = (SELECT MAX(SAL) FROM EMP);

-- ROW NUMBER
SELECT ROW_NUMBER() OVER(ORDER BY SAL), SAL FROM EMP;

-- RANK
SELECT RANK() OVER (ORDER BY SAL), SAL FROM EMP;

-- DENSE FUNCTION

SELECT DENSE_RANK() OVER (ORDER BY SAL), SAL FROM EMP;

-- WAQTD ENAME , EMPLOYEE'S DNAME , MANAGER'S NAME MANAGER'S DNAME IF EMP AND MANAGER WORKS IN SAME LOC
SELECT E.ENAME, D.DNAME, M.ENAME AS MANAGER_NAME, MD.DNAME AS MANAGER_DNAME
FROM EMP E
JOIN DEPT D ON E.DEPTNO = D.DEPTNO
LEFT JOIN EMP M ON E.MGR = M.EMPNO
LEFT JOIN DEPT MD ON M.DEPTNO = MD.DEPTNO
WHERE D.LOC = MD.LOC OR MD.LOC IS NULL;

-- Write a query to find Job And Max Sal of Emp In Each Job If The Max Sal Exceeds 2600 
SELECT JOB, MAX(SAL) AS MAX_SAL
FROM EMP
GROUP BY JOB
HAVING MAX(SAL) > 2600;


--- WAQTD ENAME , MANAGER'S SALARY AND MANAGER'S LOCATION IF MANAGER WORKS AS ''PRESIDENT'
SELECT E.ENAME, M.SAL, D.LOC
FROM EMP E
JOIN EMP M ON E.MGR = M.EMPNO
JOIN DEPT D ON M.DEPTNO = D.DEPTNO
WHERE M.JOB = 'PRESIDENT';

--  Write a query to find details of employees from destination Dallas.
SELECT E.*
FROM EMP E
JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE D.LOC = 'DALLAS';


-- WAQTD EMPLOYEE'S NAME WITH DNAME , MANAGER'S NAME WITH LOC ALONG WITH , MANAGER'S MANAGER'S NAME WITH LOC  
SELECT E.ENAME, D.DNAME, M.ENAME AS MANAGER_NAME, MD.LOC AS MANAGER_LOC, M2.ENAME AS MANAGER_MANAGER_NAME, MD2.LOC AS MANAGER_MANAGER_LOC
FROM EMP E
JOIN DEPT D ON E.DEPTNO = D.DEPTNO
LEFT JOIN EMP M ON E.MGR = M.EMPNO
LEFT JOIN DEPT MD ON M.DEPTNO = MD.DEPTNO
LEFT JOIN EMP M2 ON M.MGR = M2.EMPNO
LEFT JOIN DEPT MD2 ON M2.DEPTNO = MD2.DEPTNO;

-- Write a query to display only the repeated Salaries of Employees.
SELECT SAL
FROM EMP
GROUP BY SAL
HAVING COUNT(*) > 1;

-- Write a query to find  Deptno And Average Salary OF EMP'S For Each Department Excluding Dept 20
SELECT DEPTNO, AVG(SAL) AS AVG_SAL
FROM EMP
WHERE DEPTNO != 20
GROUP BY DEPTNO;

--  Write a query to display  Min And Max Salaries Of Each Job If Sal Is More Than 1000 And Max Sal Is Less Than 5000.
SELECT JOB, MIN(SAL) AS MIN_SAL, MAX(SAL) AS MAX_SAL
FROM EMP
WHERE SAL > 1000
GROUP BY JOB
HAVING MAX(SAL) < 5000;

-- Write a query to find Non repeated Salaries without using DISTINCT keyword
SELECT SAL
FROM EMP
GROUP BY SAL
HAVING COUNT(*) = 1;

-- Write a query to display ename ,dname and loc of the employees who are working in accounting and the ename has 'A' in it
SELECT E.ENAME, D.DNAME, D.LOC
FROM EMP E
JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE D.DNAME = 'ACCOUNTING' AND E.ENAME LIKE '%A%';